### ISSUE TITLE
smaller text on copyright on overview pages

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#41]
Within the description on the overview pages, there is a copyright notice. Anyway to make this a smaller, possibly lighter text so it isn't as dominant?

**Comment by jasonoverby** [comment]
Is it this:

<img width="1207" alt="screen shot 2016-04-03 at 7 05 30 am" src="https://cloud.githubusercontent.com/assets/13720540/14232810/e800ed74-f96a-11e5-9544-e63517a69932.png">

If so, that's part of the markdown so you'll have to go into each lesson and add some html tags like this:

`<sub><sup>Some characters used in these lessons are ©Marvel Comics Group & ©DC Comics. Doodles Academy is in no way associated with Marvel or DC Comics or their affiliates.  © info:Doodles Academy presents both public domain artworks and works that are protected by copyright in their videos and lessons. The last ones are used in accordance with fair use principle, because: the images are only being used for informational and educational purposes; the image are readily available on the internet;  If you are the copyright holder of the work of art used for Doodles-Academy.org and do not agree that its use on the site is in accordance with the fair use principle, please contact us by email.</sub></sup>`

Just cut & paste the above into the markdown for the lessons.

It will look like this:
<sub><sup>Some characters used in these lessons are ©Marvel Comics Group & ©DC Comics. Doodles Academy is in no way associated with Marvel or DC Comics or their affiliates.  © info:Doodles Academy presents both public domain artworks and works that are protected by copyright in their videos and lessons. The last ones are used in accordance with fair use principle, because: the images are only being used for informational and educational purposes; the image are readily available on the internet;  If you are the copyright holder of the work of art used for Doodles-Academy.org and do not agree that its use on the site is in accordance with the fair use principle, please contact us by email.</sub></sup>

**Comment by teaboz** [comment]
cool--thanks!


On Sun, Apr 3, 2016 at 7:18 AM, Jason Overby <notifications@github.com>
wrote:

> Is it this:
>
> [image: screen shot 2016-04-03 at 7 05 30 am]
> <https://cloud.githubusercontent.com/assets/13720540/14232810/e800ed74-f96a-11e5-9544-e63517a69932.png>
>
> If so, that's part of the markdown so you'll have to go into each lesson
> and add some html tags like this:
>
> <sub><sup>Some characters used in these lessons are ©Marvel Comics Group &
> ©DC Comics. Doodles Academy is in no way associated with Marvel or DC
> Comics or their affiliates. © info:Doodles Academy presents both public
> domain artworks and works that are protected by copyright in their videos
> and lessons. The last ones are used in accordance with fair use principle,
> because: the images are only being used for informational and educational
> purposes; the image are readily available on the internet; If you are the
> copyright holder of the work of art used for Doodles-Academy.org and do not
> agree that its use on the site is in accordance with the fair use
> principle, please contact us by email.</sub></sup>
>
> Just cut & paste the above into the markdown for the lessons.
>
> It will look like this:
> Some characters used in these lessons are ©Marvel Comics Group & ©DC
> Comics. Doodles Academy is in no way associated with Marvel or DC Comics or
> their affiliates. © info:Doodles Academy presents both public domain
> artworks and works that are protected by copyright in their videos and
> lessons. The last ones are used in accordance with fair use principle,
> because: the images are only being used for informational and educational
> purposes; the image are readily available on the internet; If you are the
> copyright holder of the work of art used for Doodles-Academy.org and do not
> agree that its use on the site is in accordance with the fair use
> principle, please contact us by email.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/41#issuecomment-204984564>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Also, look here for some general markdown styling tips:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by teaboz** [comment]
bookmarked!

On Sun, Apr 3, 2016 at 7:38 AM, Jason Overby <notifications@github.com>
wrote:

> Also, look here for some general markdown styling tips:
>
> https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/41#issuecomment-204990436>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Word!  Unfortunately I don't think there's an easy way to manipulate color (but I'll keep looking!)
