### ISSUE TITLE
Image Quilt

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#71]
Is there a way to make the image quilt on the landing page a little longer so that there is yellow at the bottom as well as the top? It looks cut off. @fuhred @jasonoverby

**Comment by jasonoverby** [comment]
@teaboz This was happening because the image is kinda small.  I fixed it by tweaking the styling a bit.

old version:
<img width="883" alt="screen shot 2016-04-07 at 4 49 53 am" src="https://cloud.githubusercontent.com/assets/13720540/14350108/36747afc-fc7c-11e5-84cd-b88be1bd3ab6.png">

new version:
<img width="879" alt="screen shot 2016-04-07 at 4 50 25 am" src="https://cloud.githubusercontent.com/assets/13720540/14350123/4894480c-fc7c-11e5-8064-bfc119032ca3.png">

**Comment by teaboz** [comment]
Great! Thanks.
