### ISSUE TITLE
Add downloadable PDFs

### ISSUE THREAD

**Issue by jasonoverby** [doodlesacademy/doodles#76]
@teaboz Where specifically on the site would you like the PDFs?

Also, I see PDFs for the Superhero lessons [here](https://drive.google.com/open?id=0B7Rpxamrcq2NNVEzSWtFd2ZYSjA) on Google Drive, but I can't find PDFs for the other lessons.  Could you point me in the right direction, or shoot those my way?

**Comment by teaboz** [comment]
On the project page, there is a section for photocopies, and has a list if there is any photocopies that go along with that lesson.

**Comment by teaboz** [comment]
The downloads should be in the drop-box folder, under curriculum & the appropriate section, usually under a 'handouts' link...let me get you some more specifics links in a sec

**Comment by teaboz** [comment]
Upper Superheroes: https://www.dropbox.com/sh/zwt5563s2iflzmh/AADHnhL7u72139TyYocfx-Eta?dl=0

**Comment by jasonoverby** [comment]
Got it.  All lessons & overviews have been updated with clickable/downloadable PDFs.

You should definitely check each one to make sure it's exactly what you want.  Let me know if you need changes to be made, and either I can do it or explain to you how to do it.

**Comment by teaboz** [comment]
@jasonoverby 
Awesome sauce! Most were perfect. But some weirdness on Artist Statements:

Superheroes Upper Academy Artist Statement--it has the lower academy (L) listed instead.
Symbol & Self Upper Artist Statement says 'doesn't exist' when I click
Symbol & Self Lower and Dream House Lower Artist Statements are actually the Upper Artist statement

And then, I don't know if this is possible, but could we attach the word document instead of the PDF to the Toy's Story U.L1.pdf? Only because the teacher should be able to edit it. If not, that's ok.  

Ultimately I want to learn how to do this for future lessons--that can be now, or Thursday if it is easier to just trade them out yourself.

**Comment by jasonoverby** [comment]
No probs!

All fixed incl. adding doc file for "A Toy's Story" in place of the pdf, but check & make sure, por favor.

& yes, let's look at it together on Thurs.

**Comment by teaboz** [comment]
Looks good! You are the best!

**Comment by jasonoverby** [comment]
Yay!  Glad it worked!
