### ISSUE TITLE
Make pdf on classes page into html

### ISSUE THREAD

**Issue by jasonoverby** [doodlesacademy/doodles#77]
It seems like it would be preferable to factor this image on the "PDX CLASS" page into html:
![pdx_class-552781220233973765b0ccb8dc4b4f014db3096620e95f2f7231a2c919ccfbe8](https://cloud.githubusercontent.com/assets/13720540/14426543/8e31758a-ffa4-11e5-82f4-f64d2d0d1dfe.png)

@fuhred @teaboz could you help with some design?  I can do the coding part once I have a better idea of how y'all want it to look.

**Comment by teaboz** [comment]
What if we mostly copied the 'about page'? So just text with some photos interspersed?

**Comment by teaboz** [comment]
![screen shot 2016-03-30 at 2 03 52 pm](https://cloud.githubusercontent.com/assets/17777336/14430895/1e830190-ffb8-11e5-856a-1f4f78c2fbe5.png)

**Comment by teaboz** [comment]
There's also the original picture:
![ariful3rdgrade copy](https://cloud.githubusercontent.com/assets/17777336/14430972/701bcc44-ffb8-11e5-9b60-49bf2d37de1c.jpg)

**Comment by fuhred** [comment]
@jasonoverby hi jason, here is a mockup we made.
https://dl.dropboxusercontent.com/u/10656919/HTML/pdx_classes.html

**Comment by jasonoverby** [comment]
@fuhred @teaboz this is great!  I will make that happen over the next week or so.

**Comment by jasonoverby** [comment]
@fuhred @tempest done!

**Comment by jasonoverby** [comment]
Note @fuhred that I altered the design slightly.  In your mock-up, in the bottom info section there are links that are underlined but that have a black font color.  I made these the standard blue we've used in the page for links b/c there's already a link at the top of the page that's blue.

Happy to make more consistent with your mock-up if that's preferable :)

**Comment by teaboz** [comment]
I just looked at this again--a couple of things:

Is the text at the top different than on the other pages? It seems large somehow. 

The third class down should be 'Friday' not Monday

And, not K. grades 1-2 (I think it said K on the flyer, but we have since changed it)

**Comment by jasonoverby** [comment]
Ack!  Inaccuracies fixed!

The text is different at the top than the other pages, but I am just going off the mock-up @fuhred made.

**Comment by teaboz** [comment]
Cool. Let's leave it until we see the style guide.

**Comment by jasonoverby** [comment]
Word

**Comment by fuhred** [comment]
I have only finished part of the style guide, but the titles/headings are
worked out:
https://dl.dropboxusercontent.com/u/10656919/HTML/typography.html

I made the page headings larger because there was too much negative space
with the older heading size.

Jason, I made some changes to the PDX classes page:

   - changed the type to be consistent with the new style guide
   - left aligned the text
   - new row lines for the table. can you do the dotted lines? if not,
   solid lines are fine.
   - changed some of the line spacing for the body paragraph text
   underneath the table


https://dl.dropboxusercontent.com/u/10656919/HTML/pdx_classes.html
